import { type EventDetail } from "@/lib/event-model";

export const sampleEvents: EventDetail[] = [
  {
    id: "sample-eventus-design",
    slug: "ai-design-creator-program",
    title: "AI활용 디자인 크리에이터 양성 교육",
    summary: "국비 전액 무료 AI 디자인 실무 교육과정. Stable Diffusion·Midjourney·Adobe Firefly를 활용한 콘텐츠 제작 역량을 체계적으로 키웁니다.",
    organizer: "더조은컴퓨터학원 일산캠퍼스",
    primarySource: "EventUs",
    primarySourceUrl: "https://event-us.kr/tjoeunis/event/112077",
    registrationUrl: "https://event-us.kr/tjoeunis/event/112077",
    city: "고양",
    venueName: "온라인 / 오프라인 병행",
    startsAt: "2026-06-02T09:30:00+09:00",
    endsAt: "2026-06-30T18:00:00+09:00",
    registrationDeadline: "2026-05-28T23:59:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "무료 Free",
    eventKind: "program",
    deliveryType: "hybrid",
    topicTags: ["AI", "디자인", "교육", "Midjourney"],
    confidenceScore: 96,
    lastCheckedAt: "2026-05-16T09:00:00+09:00",
    lastSeenAt: "2026-05-16T09:00:00+09:00",
    evidence: [
      {
        id: "evidence-eventus-design",
        sourceKind: "platform",
        sourceName: "EventUs",
        sourceUrl: "https://event-us.kr/tjoeunis/event/112077",
        discoveredFromUrl: null,
        extractedTitle: "AI활용 디자인 크리에이터 양성 교육",
        extractedStatusText: "모집중 Now Open",
        extractedPriceText: "무료 Free",
        extractedLocationText: "온라인 / 오프라인",
        extractedStartText: "06월 02일 ~ 06월 30일",
        registrationUrl: "https://event-us.kr/tjoeunis/event/112077",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 96,
        extractedAt: "2026-05-16T09:00:00+09:00",
        payload: { demo: true },
      },
    ],
    history: [
      {
        id: "snapshot-eventus-design",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 96,
        observedAt: "2026-05-16T09:00:00+09:00",
        sourceName: "EventUs",
        sourceUrl: "https://event-us.kr/tjoeunis/event/112077",
      },
    ],
  },
  {
    id: "sample-meetup-codeseoul",
    slug: "coding-with-ai-the-shift-part-1-3",
    title: "Coding with AI: The Shift - Part 1/3",
    summary: "서울 개발자 커뮤니티가 모여 AI 코딩 도구(GitHub Copilot, Cursor, Claude Code)가 바꿔놓은 개발 패러다임을 토론합니다. Microsoft Korea 오피스 무료 입장.",
    organizer: "Code Seoul",
    primarySource: "Meetup",
    primarySourceUrl: "https://www.meetup.com/ko-kr/codeseoul/events/314084114/",
    registrationUrl: "https://forms.gle/KtH8vmkMibAT7ix46",
    city: "서울",
    venueName: "Microsoft Korea Office",
    startsAt: "2026-05-24T18:00:00+09:00",
    endsAt: "2026-05-24T20:00:00+09:00",
    registrationDeadline: "2026-05-23T23:59:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "This event is FREE",
    eventKind: "meetup",
    deliveryType: "offline",
    topicTags: ["AI", "개발", "밋업", "Copilot"],
    confidenceScore: 95,
    lastCheckedAt: "2026-05-16T09:10:00+09:00",
    lastSeenAt: "2026-05-16T09:10:00+09:00",
    evidence: [
      {
        id: "evidence-meetup-codeseoul",
        sourceKind: "platform",
        sourceName: "Meetup",
        sourceUrl: "https://www.meetup.com/ko-kr/codeseoul/events/314084114/",
        discoveredFromUrl: null,
        extractedTitle: "Coding with AI: The Shift - Part 1/3",
        extractedStatusText: "Now Open",
        extractedPriceText: "This event and all Code Seoul events are FREE.",
        extractedLocationText: "Microsoft Korea Office",
        extractedStartText: "5월 24일 토요일 · PM 6:00부터 PM 8:00까지 KST",
        registrationUrl: "https://forms.gle/KtH8vmkMibAT7ix46",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 95,
        extractedAt: "2026-05-16T09:10:00+09:00",
        payload: { demo: true },
      },
    ],
    history: [
      {
        id: "snapshot-meetup-codeseoul",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 95,
        observedAt: "2026-05-16T09:10:00+09:00",
        sourceName: "Meetup",
        sourceUrl: "https://www.meetup.com/ko-kr/codeseoul/events/314084114/",
      },
    ],
  },
  {
    id: "sample-luma-ai-is-near",
    slug: "ai-is-near-seoul",
    title: "\"AI is NEAR\" Seoul",
    summary: "NEAR Protocol과 AI의 교차점을 탐구하는 서울 글로벌 밋업. Web3·AI 융합 트렌드를 선도하는 연사들의 발표와 자유 네트워킹이 진행됩니다.",
    organizer: "NEAR",
    primarySource: "Luma",
    primarySourceUrl: "https://luma.com/uab13j1b",
    registrationUrl: "https://luma.com/uab13j1b",
    city: "서울",
    venueName: "Seoul / Hybrid meetup",
    startsAt: "2026-06-21T19:00:00+09:00",
    endsAt: "2026-06-21T21:00:00+09:00",
    registrationDeadline: "2026-06-20T23:00:00+09:00",
    registrationStatus: "waitlist",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "무료 Free",
    eventKind: "meetup",
    deliveryType: "hybrid",
    topicTags: ["AI", "Web3", "블록체인", "밋업"],
    confidenceScore: 88,
    lastCheckedAt: "2026-05-16T09:20:00+09:00",
    lastSeenAt: "2026-05-16T09:20:00+09:00",
    evidence: [
      {
        id: "evidence-luma-ai-is-near",
        sourceKind: "platform",
        sourceName: "Luma",
        sourceUrl: "https://luma.com/uab13j1b",
        discoveredFromUrl: null,
        extractedTitle: "\"AI is NEAR\" Seoul",
        extractedStatusText: "Waitlist / Register",
        extractedPriceText: "무료 Free",
        extractedLocationText: "Seoul",
        extractedStartText: "6월 21일 토요일 · PM 7:00부터 PM 9:00까지 KST",
        registrationUrl: "https://luma.com/uab13j1b",
        registrationStatus: "waitlist",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 88,
        extractedAt: "2026-05-16T09:20:00+09:00",
        payload: { demo: true },
      },
    ],
    history: [
      {
        id: "snapshot-luma-ai-is-near",
        registrationStatus: "waitlist",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 88,
        observedAt: "2026-05-16T09:20:00+09:00",
        sourceName: "Luma",
        sourceUrl: "https://luma.com/uab13j1b",
      },
    ],
  },
  {
    id: "sample-onoffmix-llm-workshop",
    slug: "llm-application-workshop-seoul",
    title: "LLM 실전 애플리케이션 개발 워크숍",
    summary: "LangChain·LlamaIndex를 활용한 RAG 파이프라인 구축, 벡터 데이터베이스 연동, 프로덕션 배포까지 실습 중심으로 진행하는 무료 워크숍입니다.",
    organizer: "Seoul AI Builders",
    primarySource: "OnOffMix",
    primarySourceUrl: "https://onoffmix.com/event/demo-llm-workshop",
    registrationUrl: "https://onoffmix.com/event/demo-llm-workshop",
    city: "서울",
    venueName: "강남 스타트업 허브 3층",
    startsAt: "2026-05-31T14:00:00+09:00",
    endsAt: "2026-05-31T18:00:00+09:00",
    registrationDeadline: "2026-05-29T23:59:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "무료",
    eventKind: "seminar",
    deliveryType: "offline",
    topicTags: ["LLM", "LangChain", "RAG", "실습"],
    confidenceScore: 93,
    lastCheckedAt: "2026-05-16T10:00:00+09:00",
    lastSeenAt: "2026-05-16T10:00:00+09:00",
    evidence: [
      {
        id: "evidence-llm-workshop",
        sourceKind: "platform",
        sourceName: "OnOffMix",
        sourceUrl: "https://onoffmix.com/event/demo-llm-workshop",
        discoveredFromUrl: null,
        extractedTitle: "LLM 실전 애플리케이션 개발 워크숍",
        extractedStatusText: "신청 가능",
        extractedPriceText: "무료",
        extractedLocationText: "강남 스타트업 허브",
        extractedStartText: "5월 31일 토요일 · PM 2:00 ~ PM 6:00",
        registrationUrl: "https://onoffmix.com/event/demo-llm-workshop",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 93,
        extractedAt: "2026-05-16T10:00:00+09:00",
        payload: { demo: true },
      },
    ],
    history: [
      {
        id: "snapshot-llm-workshop",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 93,
        observedAt: "2026-05-16T10:00:00+09:00",
        sourceName: "OnOffMix",
        sourceUrl: "https://onoffmix.com/event/demo-llm-workshop",
      },
    ],
  },
  {
    id: "sample-eventus-genai-product",
    slug: "genai-product-thinking-seminar",
    title: "GenAI 기반 제품 기획 세미나",
    summary: "ChatGPT·Gemini·Claude를 실제 제품에 어떻게 녹여낼지, PM·기획자 관점에서 사례 중심으로 다루는 무료 세미나. 스타트업 실제 도입 사례 공유 포함.",
    organizer: "Product Makers Korea",
    primarySource: "EventUs",
    primarySourceUrl: "https://event-us.kr/pmk/event/genai-product",
    registrationUrl: "https://event-us.kr/pmk/event/genai-product",
    city: "서울",
    venueName: "온라인 (Zoom)",
    startsAt: "2026-06-07T14:00:00+09:00",
    endsAt: "2026-06-07T16:30:00+09:00",
    registrationDeadline: "2026-06-06T23:59:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "무료",
    eventKind: "seminar",
    deliveryType: "online",
    topicTags: ["GenAI", "PM", "제품기획", "ChatGPT"],
    confidenceScore: 90,
    lastCheckedAt: "2026-05-16T10:30:00+09:00",
    lastSeenAt: "2026-05-16T10:30:00+09:00",
    evidence: [
      {
        id: "evidence-genai-product",
        sourceKind: "platform",
        sourceName: "EventUs",
        sourceUrl: "https://event-us.kr/pmk/event/genai-product",
        discoveredFromUrl: null,
        extractedTitle: "GenAI 기반 제품 기획 세미나",
        extractedStatusText: "모집중",
        extractedPriceText: "무료",
        extractedLocationText: "온라인 (Zoom)",
        extractedStartText: "6월 7일 일요일 · PM 2:00 ~ PM 4:30",
        registrationUrl: "https://event-us.kr/pmk/event/genai-product",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 90,
        extractedAt: "2026-05-16T10:30:00+09:00",
        payload: { demo: true },
      },
    ],
    history: [
      {
        id: "snapshot-genai-product",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 90,
        observedAt: "2026-05-16T10:30:00+09:00",
        sourceName: "EventUs",
        sourceUrl: "https://event-us.kr/pmk/event/genai-product",
      },
    ],
  },
  // ── 실시간 Meetup/Eventbrite 발굴 (2026-05-16) ──────────────────
  {
    id: "sample-meetup-ai-adoption-talk",
    slug: "ai-adoption-talk-ai-seoul-may23",
    title: "✨ AI Adoption Talk — Learning & Talking on AI",
    summary: "강남역 인근 커피숍에서 매주 열리는 AI 주제 토크 모임. AI 도입 사례와 실무 적용 노하우를 영어·한국어 혼용으로 자유롭게 나눕니다. 입문자도 편하게 참여 가능.",
    organizer: "AI Seoul",
    primarySource: "Meetup",
    primarySourceUrl: "https://www.meetup.com/ai-seoul-public/events/314764876/",
    registrationUrl: "https://www.meetup.com/ai-seoul-public/events/314764876/",
    city: "서울",
    venueName: "강남역 (Gangnam Station)",
    startsAt: "2026-05-23T10:00:00+09:00",
    endsAt: "2026-05-23T12:00:00+09:00",
    registrationDeadline: "2026-05-22T23:59:00+09:00",
    registrationStatus: "waitlist",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "Free",
    eventKind: "meetup",
    deliveryType: "offline",
    topicTags: ["AI", "토크", "입문", "밋업"],
    confidenceScore: 92,
    lastCheckedAt: "2026-05-16T07:30:00+09:00",
    lastSeenAt: "2026-05-16T07:30:00+09:00",
    evidence: [{
      id: "ev-ai-adoption-talk",
      sourceKind: "platform", sourceName: "Meetup",
      sourceUrl: "https://www.meetup.com/ai-seoul-public/events/314764876/",
      discoveredFromUrl: "https://www.meetup.com/ko-KR/find/?keywords=AI&location=kr--seoul",
      extractedTitle: "✨ AI Adoption Talk - Learning & Talking on AI 👥",
      extractedStatusText: "Waitlist",
      extractedPriceText: "Free",
      extractedLocationText: "강남역 (Gangnam Station), Seoul",
      extractedStartText: "2026-05-23T10:00:00+09:00",
      registrationUrl: "https://www.meetup.com/ai-seoul-public/events/314764876/",
      registrationStatus: "waitlist", statusOrigin: "direct", priceType: "free",
      confidenceScore: 92, extractedAt: "2026-05-16T07:30:00+09:00", payload: { demo: true },
    }],
    history: [{
      id: "snap-ai-adoption-talk", registrationStatus: "waitlist", statusOrigin: "direct",
      priceType: "free", confidenceScore: 92, observedAt: "2026-05-16T07:30:00+09:00",
      sourceName: "Meetup", sourceUrl: "https://www.meetup.com/ai-seoul-public/events/314764876/",
    }],
  },
  {
    id: "sample-meetup-codeseoul-agents",
    slug: "automate-development-with-agents-codeseoul",
    title: "Automate Development with Agents",
    summary: "GitHub Copilot·Cursor·Claude Code 등 AI 에이전트를 활용해 개발 워크플로우를 자동화하는 방법을 실무 개발자들이 직접 발표합니다. Microsoft Korea Office 무료 입장.",
    organizer: "Code Seoul",
    primarySource: "Meetup",
    primarySourceUrl: "https://www.meetup.com/codeseoul/events/314473437/",
    registrationUrl: "https://forms.gle/KtH8vmkMibAT7ix46",
    city: "서울",
    venueName: "Microsoft Korea Office",
    startsAt: "2026-05-30T18:00:00+09:00",
    endsAt: "2026-05-30T20:00:00+09:00",
    registrationDeadline: "2026-05-29T23:59:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "FREE",
    eventKind: "meetup",
    deliveryType: "offline",
    topicTags: ["AI", "에이전트", "자동화", "개발"],
    confidenceScore: 95,
    lastCheckedAt: "2026-05-16T07:30:00+09:00",
    lastSeenAt: "2026-05-16T07:30:00+09:00",
    evidence: [{
      id: "ev-codeseoul-agents",
      sourceKind: "platform", sourceName: "Meetup",
      sourceUrl: "https://www.meetup.com/codeseoul/events/314473437/",
      discoveredFromUrl: "https://www.meetup.com/ko-KR/find/?keywords=AI&location=kr--seoul",
      extractedTitle: "Automate Development with Agents",
      extractedStatusText: "Open",
      extractedPriceText: "FREE",
      extractedLocationText: "Microsoft Korea Office, 서울",
      extractedStartText: "2026-05-30T18:00:00+09:00",
      registrationUrl: "https://forms.gle/KtH8vmkMibAT7ix46",
      registrationStatus: "open", statusOrigin: "direct", priceType: "free",
      confidenceScore: 95, extractedAt: "2026-05-16T07:30:00+09:00", payload: { demo: true },
    }],
    history: [{
      id: "snap-codeseoul-agents", registrationStatus: "open", statusOrigin: "direct",
      priceType: "free", confidenceScore: 95, observedAt: "2026-05-16T07:30:00+09:00",
      sourceName: "Meetup", sourceUrl: "https://www.meetup.com/codeseoul/events/314473437/",
    }],
  },
  {
    id: "sample-meetup-owasp-ai-vuln",
    slug: "owasp-seoul-ai-vulnerability-seminar-may26",
    title: "OWASP Seoul 5월 세미나: AI 딸깍 취약점 딸깍",
    summary: "AI를 활용한 취약점 탐지 사례 발표. 실제 CVE 발굴 과정부터 패치까지 보안 전문가가 직접 설명합니다. OWASP Seoul Chapter 정기 오프라인 세미나.",
    organizer: "OWASP Seoul Chapter",
    primarySource: "Meetup",
    primarySourceUrl: "https://www.meetup.com/owasp-seoul/events/314395456/",
    registrationUrl: "https://www.meetup.com/owasp-seoul/events/314395456/",
    city: "서울",
    venueName: "D Camp (디캠프)",
    startsAt: "2026-05-26T19:00:00+09:00",
    endsAt: "2026-05-26T21:30:00+09:00",
    registrationDeadline: "2026-05-25T23:59:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "무료",
    eventKind: "seminar",
    deliveryType: "offline",
    topicTags: ["AI", "보안", "OWASP", "취약점"],
    confidenceScore: 93,
    lastCheckedAt: "2026-05-16T07:30:00+09:00",
    lastSeenAt: "2026-05-16T07:30:00+09:00",
    evidence: [{
      id: "ev-owasp-ai-vuln",
      sourceKind: "platform", sourceName: "Meetup",
      sourceUrl: "https://www.meetup.com/owasp-seoul/events/314395456/",
      discoveredFromUrl: "https://www.meetup.com/ko-KR/find/?keywords=AI&location=kr--seoul",
      extractedTitle: "OWASP Seoul 5월 세미나: AI 딸깍 취약점 딸깍",
      extractedStatusText: "Open — 130명 참석자",
      extractedPriceText: "무료",
      extractedLocationText: "D Camp, 서울",
      extractedStartText: "2026-05-26T19:00:00+09:00",
      registrationUrl: "https://www.meetup.com/owasp-seoul/events/314395456/",
      registrationStatus: "open", statusOrigin: "direct", priceType: "free",
      confidenceScore: 93, extractedAt: "2026-05-16T07:30:00+09:00", payload: { demo: true },
    }],
    history: [{
      id: "snap-owasp-ai-vuln", registrationStatus: "open", statusOrigin: "direct",
      priceType: "free", confidenceScore: 93, observedAt: "2026-05-16T07:30:00+09:00",
      sourceName: "Meetup", sourceUrl: "https://www.meetup.com/owasp-seoul/events/314395456/",
    }],
  },
  {
    id: "sample-meetup-mug-rag",
    slug: "mug-gdg-local-rag-prototyping-may29",
    title: "[MUG x GDG] 하루 만에 끝내는 로컬 RAG 프로토타이핑",
    summary: "Gemma 최신 모델 + Voyage AI + MongoDB로 완성하는 Full 로컬 RAG. MongoDB Seoul User Group과 GDG Korea 공동 주최. 구글 스타트업 캠퍼스에서 무료 진행.",
    organizer: "Seoul MongoDB User Group × GDG Korea",
    primarySource: "Meetup",
    primarySourceUrl: "https://www.meetup.com/mongodb-usergroup-seoul/events/314765122/",
    registrationUrl: "https://www.meetup.com/mongodb-usergroup-seoul/events/314765122/",
    city: "서울",
    venueName: "구글 스타트업 캠퍼스",
    startsAt: "2026-05-29T19:00:00+09:00",
    endsAt: "2026-05-29T21:30:00+09:00",
    registrationDeadline: "2026-05-28T23:59:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "무료",
    eventKind: "seminar",
    deliveryType: "offline",
    topicTags: ["RAG", "Gemma", "MongoDB", "LLM", "실습"],
    confidenceScore: 94,
    lastCheckedAt: "2026-05-16T07:30:00+09:00",
    lastSeenAt: "2026-05-16T07:30:00+09:00",
    evidence: [{
      id: "ev-mug-rag",
      sourceKind: "platform", sourceName: "Meetup",
      sourceUrl: "https://www.meetup.com/mongodb-usergroup-seoul/events/314765122/",
      discoveredFromUrl: "https://www.meetup.com/ko-KR/find/?keywords=AI&location=kr--seoul",
      extractedTitle: "[MUG x GDG] 하루 만에 끝내는 로컬 RAG 프로토타이핑",
      extractedStatusText: "Open — 50명 참석자",
      extractedPriceText: "무료",
      extractedLocationText: "구글 스타트업 캠퍼스, Seoul",
      extractedStartText: "2026-05-29T19:00:00+09:00",
      registrationUrl: "https://www.meetup.com/mongodb-usergroup-seoul/events/314765122/",
      registrationStatus: "open", statusOrigin: "direct", priceType: "free",
      confidenceScore: 94, extractedAt: "2026-05-16T07:30:00+09:00", payload: { demo: true },
    }],
    history: [{
      id: "snap-mug-rag", registrationStatus: "open", statusOrigin: "direct",
      priceType: "free", confidenceScore: 94, observedAt: "2026-05-16T07:30:00+09:00",
      sourceName: "Meetup", sourceUrl: "https://www.meetup.com/mongodb-usergroup-seoul/events/314765122/",
    }],
  },
  {
    id: "sample-eventbrite-seoul-tech-mixer",
    slug: "seoul-tech-mixer-ai-it-may22",
    title: "Seoul Tech Mixer and Social (Tech / AI / Data / IT) ✨",
    summary: "퇴근 후 서울 브루어리에서 열리는 Tech·AI·Data 종사자 네트워킹 파티. 명함 없이 편하게 오는 자유로운 분위기. Eventbrite 무료 등록.",
    organizer: "Seoul Tech Community",
    primarySource: "Eventbrite",
    primarySourceUrl: "https://www.eventbrite.com/e/seoul-tech-mixer-and-social-tech-ai-data-it-tickets-1987413369889",
    registrationUrl: "https://www.eventbrite.com/e/seoul-tech-mixer-and-social-tech-ai-data-it-tickets-1987413369889",
    city: "서울",
    venueName: "Seoul Brewery",
    startsAt: "2026-05-22T19:00:00+09:00",
    endsAt: "2026-05-22T22:00:00+09:00",
    registrationDeadline: "2026-05-22T18:00:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "Free",
    eventKind: "networking",
    deliveryType: "offline",
    topicTags: ["AI", "네트워킹", "테크", "파티"],
    confidenceScore: 89,
    lastCheckedAt: "2026-05-16T07:30:00+09:00",
    lastSeenAt: "2026-05-16T07:30:00+09:00",
    evidence: [{
      id: "ev-seoul-tech-mixer",
      sourceKind: "platform", sourceName: "Eventbrite",
      sourceUrl: "https://www.eventbrite.com/e/seoul-tech-mixer-and-social-tech-ai-data-it-tickets-1987413369889",
      discoveredFromUrl: "https://www.eventbrite.com/d/south-korea--seoul/free--events/ai/",
      extractedTitle: "Seoul Tech Mixer and Social (Tech / AI / Data / IT) ✨",
      extractedStatusText: "Register",
      extractedPriceText: "Free",
      extractedLocationText: "Seoul Brewery, Seoul",
      extractedStartText: "2026-05-22T19:00:00+09:00",
      registrationUrl: "https://www.eventbrite.com/e/seoul-tech-mixer-and-social-tech-ai-data-it-tickets-1987413369889",
      registrationStatus: "open", statusOrigin: "direct", priceType: "free",
      confidenceScore: 89, extractedAt: "2026-05-16T07:30:00+09:00", payload: { demo: true },
    }],
    history: [{
      id: "snap-seoul-tech-mixer", registrationStatus: "open", statusOrigin: "direct",
      priceType: "free", confidenceScore: 89, observedAt: "2026-05-16T07:30:00+09:00",
      sourceName: "Eventbrite", sourceUrl: "https://www.eventbrite.com/e/seoul-tech-mixer-and-social-tech-ai-data-it-tickets-1987413369889",
    }],
  },
  {
    id: "sample-meetup-awskrug-eks",
    slug: "awskrug-eks-container-deep-dive-may29",
    title: "AWSKRUG #container EKS & Container Deep Dive Night",
    summary: "AWS EKS 스터디 4기 졸업 발표 + 실전 컨테이너 운영 노하우 공유. AWSKRUG 공식 소모임으로 Centerfield(강남)에서 무료 진행. AI 인프라 운영에 관심 있는 DevOps·SRE에게 추천.",
    organizer: "AWSKRUG - AWS 한국사용자모임",
    primarySource: "Meetup",
    primarySourceUrl: "https://www.meetup.com/awskrug/events/314686543/",
    registrationUrl: "https://www.meetup.com/awskrug/events/314686543/",
    city: "서울",
    venueName: "Centerfield (강남)",
    startsAt: "2026-05-29T19:00:00+09:00",
    endsAt: "2026-05-29T21:30:00+09:00",
    registrationDeadline: "2026-05-28T23:59:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "무료",
    eventKind: "seminar",
    deliveryType: "offline",
    topicTags: ["AWS", "EKS", "DevOps", "컨테이너"],
    confidenceScore: 90,
    lastCheckedAt: "2026-05-16T07:30:00+09:00",
    lastSeenAt: "2026-05-16T07:30:00+09:00",
    evidence: [{
      id: "ev-awskrug-eks",
      sourceKind: "platform", sourceName: "Meetup",
      sourceUrl: "https://www.meetup.com/awskrug/events/314686543/",
      discoveredFromUrl: "https://www.meetup.com/ko-KR/find/?keywords=AI&location=kr--seoul",
      extractedTitle: "AWSKRUG #container 🐳 EKS & Container Deep Dive Night",
      extractedStatusText: "Open — 8 좌석 남음",
      extractedPriceText: "free",
      extractedLocationText: "Centerfield, Gangnam-gu",
      extractedStartText: "2026-05-29T19:00:00+09:00",
      registrationUrl: "https://www.meetup.com/awskrug/events/314686543/",
      registrationStatus: "open", statusOrigin: "direct", priceType: "free",
      confidenceScore: 90, extractedAt: "2026-05-16T07:30:00+09:00", payload: { demo: true },
    }],
    history: [{
      id: "snap-awskrug-eks", registrationStatus: "open", statusOrigin: "direct",
      priceType: "free", confidenceScore: 90, observedAt: "2026-05-16T07:30:00+09:00",
      sourceName: "Meetup", sourceUrl: "https://www.meetup.com/awskrug/events/314686543/",
    }],
  },
  {
    id: "sample-luma-ai-startup-pitch",
    slug: "ai-startup-demo-day-seoul",
    title: "AI Startup Demo Day Seoul 2026",
    summary: "서울 AI 스타트업 10팀이 투자자·파트너 앞에서 제품을 발표하는 데모데이. 관람객은 무료 입장 가능하며 네트워킹 시간도 별도로 주어집니다.",
    organizer: "Korea AI Startup Alliance",
    primarySource: "Luma",
    primarySourceUrl: "https://luma.com/ai-demo-day-seoul-2026",
    registrationUrl: "https://luma.com/ai-demo-day-seoul-2026",
    city: "서울",
    venueName: "코엑스 스타트업브랜치 B홀",
    startsAt: "2026-06-14T13:00:00+09:00",
    endsAt: "2026-06-14T18:00:00+09:00",
    registrationDeadline: "2026-06-12T23:59:00+09:00",
    registrationStatus: "open",
    statusOrigin: "direct",
    priceType: "free",
    priceText: "무료 (관람객)",
    eventKind: "demo_day",
    deliveryType: "offline",
    topicTags: ["AI", "스타트업", "데모데이", "투자"],
    confidenceScore: 87,
    lastCheckedAt: "2026-05-16T11:00:00+09:00",
    lastSeenAt: "2026-05-16T11:00:00+09:00",
    evidence: [
      {
        id: "evidence-ai-demo-day",
        sourceKind: "platform",
        sourceName: "Luma",
        sourceUrl: "https://luma.com/ai-demo-day-seoul-2026",
        discoveredFromUrl: null,
        extractedTitle: "AI Startup Demo Day Seoul 2026",
        extractedStatusText: "Register",
        extractedPriceText: "무료 (관람객)",
        extractedLocationText: "코엑스 스타트업브랜치",
        extractedStartText: "6월 14일 일요일 · PM 1:00 ~ PM 6:00",
        registrationUrl: "https://luma.com/ai-demo-day-seoul-2026",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 87,
        extractedAt: "2026-05-16T11:00:00+09:00",
        payload: { demo: true },
      },
    ],
    history: [
      {
        id: "snapshot-ai-demo-day",
        registrationStatus: "open",
        statusOrigin: "direct",
        priceType: "free",
        confidenceScore: 87,
        observedAt: "2026-05-16T11:00:00+09:00",
        sourceName: "Luma",
        sourceUrl: "https://luma.com/ai-demo-day-seoul-2026",
      },
    ],
  },
];
